# Form implementation generated from reading ui file 'D:\生产实习-火灾检测\界面UI\test_1.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtMultimediaWidgets import QVideoWidget
from PyQt6.QtWidgets import QVBoxLayout


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(824, 719)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setObjectName("main_layout")
        self.top_layout = QtWidgets.QHBoxLayout()
        self.top_layout.setContentsMargins(5, 5, 5, 5)
        self.top_layout.setSpacing(10)
        self.top_layout.setObjectName("top_layout")

        self.source_data = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source_data.sizePolicy().hasHeightForWidth())
        self.source_data.setSizePolicy(sizePolicy)
        self.source_data.setScaledContents(True)  # 允许QLabel自动调整图片大小
        self.source_data.setStyleSheet("QLabel{\n"
"        background-color : white;\n"
"        border : 1px solid #cccccc;\n"
"        border-radius : 5px;\n"
"        padding: 5px;\n"
"}")
        self.source_data.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.source_data.setObjectName("source_data")
        self.top_layout.addWidget(self.source_data)

        # # 视频播放组件 QVideoWidget, 将其设置为source_data的子组件
        # self.video_widget = QVideoWidget(parent=self.source_data)
        # self.video_widget.setObjectName("video_widget")
        # self.video_widget.hide()  # 默认隐藏
        #
        # # 使用布局管理器，将布局赋给source_data并将video_widget加入此布局,以确保两者位置大小相一致
        # layout = QVBoxLayout(self.source_data)
        # layout.addWidget(self.video_widget)
        # layout.setContentsMargins(0, 0, 0, 0)  # 去除布局边距

        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(200, 256))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\生产实习-火灾检测\\界面UI\\../../浏览器下载/更多萌宠.png"))
        self.label.setObjectName("label")
        self.top_layout.addWidget(self.label)
        self.result_data = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_data.sizePolicy().hasHeightForWidth())
        self.result_data.setSizePolicy(sizePolicy)
        self.result_data.setScaledContents(True)  # 允许QLabel自动调整图片大小
        self.result_data.setStyleSheet("QLabel{\n"
"        background-color : white;\n"
"        border : 1px solid #cccccc;\n"
"        border-radius : 5px;\n"
"        padding: 5px;\n"
"}")
        self.result_data.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.result_data.setObjectName("result_data")
        self.top_layout.addWidget(self.result_data)
        self.result_data.setFixedSize(640, 480)
        self.source_data.setFixedSize(640, 480)
        self.main_layout.addLayout(self.top_layout)
        self.mid_layout = QtWidgets.QHBoxLayout()
        self.mid_layout.setObjectName("mid_layout")
        self.select_layout = QtWidgets.QVBoxLayout()
        self.select_layout.setObjectName("select_layout")
        self.select_model_path = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_model_path.sizePolicy().hasHeightForWidth())
        self.select_model_path.setSizePolicy(sizePolicy)
        self.select_model_path.setMaximumSize(QtCore.QSize(120, 500))
        self.select_model_path.setStyleSheet("QPushButton{\n"
"        background-color : white;\n"
"        border : 1px solid #cccccc;\n"
"        border-radius : 5px;\n"
"        padding: 5px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\生产实习-火灾检测\\界面UI\\../../浏览器下载/柴犬.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.select_model_path.setIcon(icon)
        self.select_model_path.setObjectName("select_model_path")
        self.select_layout.addWidget(self.select_model_path)
        self.model_path = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.model_path.setMaximumSize(QtCore.QSize(16777215, 41))
        self.model_path.setStyleSheet("QTextEdit{\n"
"        background-color : white;\n"
"        border : 1px solid #cccccc;\n"
"        border-radius : 5px;\n"
"        padding: 5px;\n"
"}")
        self.model_path.setReadOnly(True)
        self.model_path.setObjectName("model_path")
        self.select_layout.addWidget(self.model_path)
        self.data_class = QtWidgets.QComboBox(parent=self.centralwidget)
        self.data_class.setMaximumSize(QtCore.QSize(120, 500))
        self.data_class.setStyleSheet("background-color : white;\n"
"        border : 1px solid #cccccc;\n"
"        border-radius : 5px;\n"
"        padding: 5px;")
        self.data_class.setEditable(False)
        self.data_class.setMinimumContentsLength(3)
        self.data_class.setObjectName("data_class")
        self.data_class.addItem("")
        self.data_class.addItem("")
        self.data_class.addItem("")
        self.select_layout.addWidget(self.data_class)
        self.select_data_path = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_data_path.sizePolicy().hasHeightForWidth())
        self.select_data_path.setSizePolicy(sizePolicy)
        self.select_data_path.setMaximumSize(QtCore.QSize(120, 500))
        self.select_data_path.setStyleSheet("QPushButton{\n"
"        background-color : white;\n"
"        border : 1px solid #cccccc;\n"
"        border-radius : 5px;\n"
"        padding: 5px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\生产实习-火灾检测\\界面UI\\../../浏览器下载/哈士奇.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.select_data_path.setIcon(icon1)
        self.select_data_path.setObjectName("select_data_path")
        self.select_layout.addWidget(self.select_data_path)
        self.data_path = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.data_path.setMaximumSize(QtCore.QSize(16777215, 41))
        self.data_path.setStyleSheet("QTextEdit{\n"
"        background-color : white;\n"
"        border : 1px solid #cccccc;\n"
"        border-radius : 5px;\n"
"        padding: 5px;\n"
"}")
        self.data_path.setReadOnly(True)
        self.data_path.setObjectName("data_path")
        self.select_layout.addWidget(self.data_path)
        self.parameter_layout = QtWidgets.QHBoxLayout()
        self.parameter_layout.setObjectName("parameter_layout")
        self.belief = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.belief.sizePolicy().hasHeightForWidth())
        self.belief.setSizePolicy(sizePolicy)
        self.belief.setMaximumSize(QtCore.QSize(120, 500))
        self.belief.setStyleSheet("QPushButton{\n"
"        background-color : white;\n"
"        border : 1px solid #cccccc;\n"
"        border-radius : 5px;\n"
"        padding: 5px;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\生产实习-火灾检测\\界面UI\\../../浏览器下载/仓鼠.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.belief.setIcon(icon2)
        self.belief.setObjectName("belief")
        self.parameter_layout.addWidget(self.belief)
        self.belief_value = QtWidgets.QLineEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.belief_value.sizePolicy().hasHeightForWidth())
        self.belief_value.setSizePolicy(sizePolicy)
        self.belief_value.setMaximumSize(QtCore.QSize(1000, 1000))
        self.belief_value.setStyleSheet("QLineEdit{\n"
"        background-color : white;\n"
"        border : 1px solid #cccccc;\n"
"        border-radius : 5px;\n"
"        padding: 5px;\n"
"}")
        self.belief_value.setText("")
        self.belief_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.belief_value.setObjectName("belief_value")
        self.parameter_layout.addWidget(self.belief_value)
        self.IOU = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IOU.sizePolicy().hasHeightForWidth())
        self.IOU.setSizePolicy(sizePolicy)
        self.IOU.setMaximumSize(QtCore.QSize(120, 500))
        self.IOU.setStyleSheet("QPushButton{\n"
"        background-color : white;\n"
"        border : 1px solid #cccccc;\n"
"        border-radius : 5px;\n"
"        padding: 5px;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:\\生产实习-火灾检测\\界面UI\\../../浏览器下载/边牧.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.IOU.setIcon(icon3)
        self.IOU.setObjectName("IOU")
        self.parameter_layout.addWidget(self.IOU)
        self.IOU_value = QtWidgets.QLineEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IOU_value.sizePolicy().hasHeightForWidth())
        self.IOU_value.setSizePolicy(sizePolicy)
        self.IOU_value.setMaximumSize(QtCore.QSize(1000, 1000))
        self.IOU_value.setStyleSheet("QLineEdit{\n"
"        background-color : white;\n"
"        border : 1px solid #cccccc;\n"
"        border-radius : 5px;\n"
"        padding: 5px;\n"
"}")
        self.IOU_value.setText("")
        self.IOU_value.setReadOnly(True)
        self.IOU_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.IOU_value.setObjectName("IOU_value")
        self.parameter_layout.addWidget(self.IOU_value)
        self.select_layout.addLayout(self.parameter_layout)
        self.select_layout.setStretch(0, 1)
        self.select_layout.setStretch(1, 1)
        self.select_layout.setStretch(2, 1)
        self.select_layout.setStretch(3, 1)
        self.select_layout.setStretch(4, 1)
        self.select_layout.setStretch(5, 1)
        self.mid_layout.addLayout(self.select_layout)
        """
        self.text_information = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_information.sizePolicy().hasHeightForWidth())
        self.text_information.setSizePolicy(sizePolicy)
        self.text_information.setMaximumSize(QtCore.QSize(1000, 1000))
        self.text_information.setStyleSheet("QLabel{\n"
"        background-color : white;\n"
"        border : 1px solid #cccccc;\n"
"        border-radius : 5px;\n"
"        padding: 5px;\n"
"}")
        self.text_information.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.text_information.setObjectName("text_information")
        self.mid_layout.addWidget(self.text_information)
        
        """
        self.text_information = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_information.sizePolicy().hasHeightForWidth())
        self.text_information.setSizePolicy(sizePolicy)
        self.text_information.setMaximumSize(QtCore.QSize(1000, 1000))
        self.text_information.setStyleSheet("QPlainTextEdit{\n"
                                            " background-color : white;\n"
                                            " border : 1px solid #cccccc;\n"
                                            " border-radius : 5px;\n"
                                            " padding: 5px;\n"
                                            "}")
        # self.text_information.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.text_information.setReadOnly(True)  # 如果你希望 QPlainTextEdit 不可编辑，可以加上这一行
        self.text_information.setObjectName("text_information")
        self.mid_layout.addWidget(self.text_information)

        self.mid_layout.setStretch(0, 2)
        self.mid_layout.setStretch(1, 1)
        self.main_layout.addLayout(self.mid_layout)
        self.behind_layout = QtWidgets.QHBoxLayout()
        self.behind_layout.setContentsMargins(-1, 10, -1, 10)
        self.behind_layout.setSpacing(15)
        self.behind_layout.setObjectName("behind_layout")
        self.start_button = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_button.sizePolicy().hasHeightForWidth())
        self.start_button.setSizePolicy(sizePolicy)
        self.start_button.setMaximumSize(QtCore.QSize(120, 50))
        self.start_button.setStyleSheet("QPushButton{\n"
"        background-color : white;\n"
"        border : 1px solid #cccccc;\n"
"        border-radius : 5px;\n"
"        padding: 5px;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("D:\\生产实习-火灾检测\\界面UI\\../../浏览器下载/可达鸭.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.start_button.setIcon(icon4)
        self.start_button.setObjectName("start_button")
        self.behind_layout.addWidget(self.start_button)
        self.stop_button = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_button.sizePolicy().hasHeightForWidth())
        self.stop_button.setSizePolicy(sizePolicy)
        self.stop_button.setMaximumSize(QtCore.QSize(120, 50))
        self.stop_button.setStyleSheet("QPushButton{\n"
"        background-color : white;\n"
"        border : 1px solid #cccccc;\n"
"        border-radius : 5px;\n"
"        padding: 5px;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("D:\\生产实习-火灾检测\\界面UI\\../../浏览器下载/三花猫.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.stop_button.setIcon(icon5)
        self.stop_button.setObjectName("stop_button")
        self.behind_layout.addWidget(self.stop_button)
        self.end_button = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.end_button.sizePolicy().hasHeightForWidth())
        self.end_button.setSizePolicy(sizePolicy)
        self.end_button.setMaximumSize(QtCore.QSize(120, 50))
        self.end_button.setStyleSheet("QPushButton{\n"
"        background-color : white;\n"
"        border : 1px solid #cccccc;\n"
"        border-radius : 5px;\n"
"        padding: 5px;\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("D:\\生产实习-火灾检测\\界面UI\\../../浏览器下载/布偶猫.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.end_button.setIcon(icon6)
        self.end_button.setObjectName("end_button")
        self.behind_layout.addWidget(self.end_button)
        self.save_button = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_button.sizePolicy().hasHeightForWidth())
        self.save_button.setSizePolicy(sizePolicy)
        self.save_button.setMaximumSize(QtCore.QSize(120, 50))
        self.save_button.setStyleSheet("QPushButton{\n"
"        background-color : white;\n"
"        border : 1px solid #cccccc;\n"
"        border-radius : 5px;\n"
"        padding: 5px;\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("D:\\生产实习-火灾检测\\界面UI\\../../浏览器下载/暹罗猫.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.save_button.setIcon(icon7)
        self.save_button.setObjectName("save_button")
        self.behind_layout.addWidget(self.save_button)
        self.log_button = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_button.sizePolicy().hasHeightForWidth())
        self.log_button.setSizePolicy(sizePolicy)
        self.log_button.setMaximumSize(QtCore.QSize(120, 50))
        self.log_button.setStyleSheet("QPushButton{\n"
"        background-color : white;\n"
"        border : 1px solid #cccccc;\n"
"        border-radius : 5px;\n"
"        padding: 5px;\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("D:\\生产实习-火灾检测\\界面UI\\../../浏览器下载/田园犬.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.log_button.setIcon(icon8)
        self.log_button.setObjectName("log_button")
        self.behind_layout.addWidget(self.log_button)
        self.main_layout.addLayout(self.behind_layout)
        self.main_layout.setStretch(0, 2)
        self.main_layout.setStretch(1, 2)
        self.main_layout.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.main_layout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.source_data.setText(_translate("MainWindow", "原始数据"))
        self.result_data.setText(_translate("MainWindow", "检测结果"))
        self.select_model_path.setText(_translate("MainWindow", "选择模型路径："))
        self.data_class.setItemText(0, _translate("MainWindow", "图片"))
        self.data_class.setItemText(1, _translate("MainWindow", "视频"))
        self.data_class.setItemText(2, _translate("MainWindow", "摄像头"))
        self.select_data_path.setText(_translate("MainWindow", "选择数据路径："))
        self.belief.setText(_translate("MainWindow", "置信度："))
        self.IOU.setText(_translate("MainWindow", "频率："))
        # self.text_information.setText(_translate("MainWindow", "文本信息"))
        self.start_button.setText(_translate("MainWindow", "开始检测"))
        self.stop_button.setText(_translate("MainWindow", "暂停检测"))
        self.end_button.setText(_translate("MainWindow", "结束检测"))
        self.save_button.setText(_translate("MainWindow", "保存结果"))
        self.log_button.setText(_translate("MainWindow", "查看日志"))
